### ISSUE TITLE
Consider re-enalbing LTO

### ISSUE THREAD

**Issue by zamazan4ik** [wcampbell0x2a/zerus#105]
Hi!

I found that LTO for the project was enabled in [this](https://github.com/wcampbell0x2a/zerus/commit/048e24f2f9c833605df02350f21dc31abf651ccd) commit but later was disabled [here](https://github.com/wcampbell0x2a/zerus/commit/8fb3843716dcf9d54d078773a693d37470389681). Unfortunately, I didn't find the reason for this decision in the commit history.

Could you please elaborate a bit more on why did you disable LTO for the project? If this is due to increased compile time and it's critical for the project, did you evaluate enabling ThinLTO instead? Or maybe LTO was just mistakenly disabled - who knows :)

According to my quick tests, adding `lto = true` to the Release profile reduces the binary size from 12 Mib to 10 Mib - quite a good improvement.

Thank you.

**Comment by wcampbell0x2a** [comment]
Added in https://github.com/wcampbell0x2a/zerus/releases/tag/v0.10.1
